### ISSUE TITLE
Arduino programming language definition is incorrect

### ISSUE THREAD

**Issue by modalpdx** [lyzadanger/JSoT#16]
Howdy,

I popped in to see where the glossary stands and I noticed the definition of "Arduino (programming language)" is incorrect. Here's what it currently says:

  Arduino (programming language): any C or C++ that avr-gcc can compile

Unfortunately, this isn't accurate. Arduino programming is to avr-gcc what jQuery is to JavaScript: it's a simplified library of functions, nothing more. The avr-gcc compiler is actually completely independent of Arduino's ecosystem, as is avrdude and other items packaged with the Arduino IDE.

I don't have a better alternative definition to offer, otherwise I'd just edit the definition and submit a pull request. However, it may be worth removing the definition until a better one comes along? I'll leave it to you to decide.

Thanks,

E.

**Comment by lyzadanger** [comment]
@modalpdx Why don't you submit a PR that simply obliterates the entry for now? This was me—it was something I saw on the Internet somewhere :). Guess I should do some more research.

**Comment by modalpdx** [comment]
'Kay, I'll freshen my source tree for the glossary and get a pull request going. Thanks!
