### ISSUE TITLE
Nail Down Definition Format

### ISSUE THREAD

**Issue by lyzadanger** [lyzadanger/JSoT#5]
I've been writing terms/definitions that follow these conventions:
- The "spelled-out" version of the term (e.g. _Random Access Memory_ ) is the "main" term.
- Acronym forms have their own entry, but link to the spelled-out variant.

e.g.:

```
* **RAM**: _See [Random Access Memory](#random-access-memory)_
* **Random Access Memory**<a name="random-access-memory"></a>:
    Definition here...
```

The benefits of this are:
- Emphasis on the expanded variants of terms as the canonical term
- Allows for an entry for all acronym or other forms in alphabetical order, making it easier for someone to scan the entries if they're looking for something

However, it could be perhaps overengineered or pedantic if:
- Terms are near each other alphabetically (e.g. _RAM_ will be quite near _Random Access Memory_)
- An acronym really is the canonical term (I mean, who really uses _Complementary Metal Oxide Semiconductor_ in day-to-day speech?)

_However_, combining acronym and expanded terms has a couple of drawbacks, too:
- Either the acronym or the expanded form will potentially not be in correct alphabetical order 
- What if there is more than one acronym/synonym for the term?

Because of that I lean toward my original over-pedantic form, but I wanted to get y'all's opinions before railroading this through :D. 

/cc @modalpdx @samjulien

**Comment by modalpdx** [comment]
Argh, I see why this could be an issue. I originally liked the idea of "Expanded Form (EF)" all on one line, but I now see how that could confuse someone that does not know what an acronym expands to. In the example I just made, "EF" and "Expanded Form" would probably be far apart.

With this in mind, I'm leaning toward giving the acronym its own entry along with a "see ____" link, and if the two are stacked on top of each other, I think that's not a big deal.

Yay voting! :)

/cc @lyzadanger @samjulien

**Comment by samjulien** [comment]
It looks like SJSJ lets go of the full spelling altogether in the entry names (e.g. IIFE, not immediately invoked function expression). I think most people look up acronyms because they _don't_ know what they stand for really. If there's more than one option, couldn't we just link to the primary one? 

/cc @lyzadanger @modalpdx

**Comment by lyzadanger** [comment]
I think the outstanding question is whether we should have a separate entry for the acronym version, e.g.

```
* **Random Access Memory (RAM)**
```

versus

```
* **RAM** (...)
* **Random Access Memory** (...)
```

As a child of an editor and related to librarians, I lean toward the latter because it will retain alphabetical order for all things. I also lean toward being exhaustive with entries, even if it's a little...overboard :)

**Comment by samjulien** [comment]
But why not just:

```
* **RAM**: random access memory //etc.
```

a la SJSJ?

**Comment by lyzadanger** [comment]
@samjulien Part of the reason for this excessively detailed issue is that this is the one place I was deviating a little from SJSJ's style. :)

I would personally _prefer_ that SJSJ did have an entry for both `IIFE` and `Immediately-invoked function expression`. I like the idea of having entries for all the possible mutations, such that we're not creating an acronym forest necessarily. 

I think a better example than `RAM` might be `alternating current`. I could see someone arriving and looking for _both_ `alternating current` and `AC`. 

Eh...I'm still noodling on this...

**Comment by samjulien** [comment]
Ah, I see what you mean. I guess it depends on whether the goal is cataloging all possible options or going with what we think is the most common use case. I don't feel strongly either way. We can go with what you're saying and see how it evolves over time. I just wonder how many of entries will end up amounting to "ABC - see Alphabet Block Corporation."

**Comment by lyzadanger** [comment]
OK, how about this...

Take a gander at the [current commit of the main README](https://github.com/lyzadanger/JSoT/blob/4539ec30efe13230d4e95d1cfc8bbe3a790f2c18/README.md)

You'll notice what I would call _common sense_. In some cases, the expanded variant is treated as the "main" definition, but in certain cases, the acronym is. Example: `EEPROM` vs. `Electrically-erasable Programmable Read-only Memory`. I've treated `EEPROM` as the main variant. 

For now I suggest we keep on keepin' on. I'll play an editorial/formatting role for the time being and if things get unwieldy we can revisit?

**Comment by modalpdx** [comment]
"Keep on keepin' on" sounds like a good plan. 

I almost wish the content was in a flat file database of some kind so it can be easily rescrambulated with an awk script. In fact, when content is all filled in I may take the README.md file and make a flat file DB (it's easy peasy) just in case it will be useful later, like maybe if the definitions need to be in a different format for Slack to read them, or whatever. For now, markdown and "common sense" formatting is all Imma gunna worry about. 

Thanks y'all! This is going to be an awesome resource. 

E.

**Comment by samjulien** [comment]
I'm down with keepin' on, I think we're making good decisions as it is.

**Comment by lyzadanger** [comment]
Cool. I'll close this but glad we had the chat for posterity. I'm flexible as we go forward!

**Comment by samjulien** [comment]
Me too! :)
