### ISSUE TITLE
Provide capacitor image credit

### ISSUE THREAD

**Issue by lyzadanger** [lyzadanger/JSoT#8]
After I merged #7 I noticed the lovely photo in the capacitor glossary entry and I wondered if it were possible to add an image credit for that. I imagine you picked it up from Wikipedia? Even if it's public domain, I like to give props when possible :).

**Comment by samjulien** [comment]
Ah shoot, I put it in the markdown and thought it would be an alt tag. No problem, I'll get it done.

**Comment by lyzadanger** [comment]
This is done, right? as of #11 ?

**Comment by samjulien** [comment]
Yep!
